- name: Update Workstations OS
  hosts: workstations
  become: true
  roles:
    - { role: debian, when: ansible_os_family == "Debian" }
    - { role: centos, when: ansible_os_family == "RedHat" }
   
- name: Update web_servers OS
  hosts: web_servers
  become: true
  roles:
    - { role: debian, when: ansible_os_family == "Debian" }
    - { role: centos, when: ansible_os_family == "RedHat" }

- name: Update db_servers OS
  hosts: db_servers
  become: true
  roles:
    - { role: debian, when: ansible_os_family == "Debian" }
    - { role: centos, when: ansible_os_family == "RedHat" }

- name: Update file_servers OS
  hosts: file_servers
  become: true
  roles:
    - { role: debian, when: ansible_os_family == "Debian" }
    - { role: centos, when: ansible_os_family == "RedHat" }
